spring:
  kafka:
    producer:
      client-id: json-sample-simulator
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false
  cloud:
    stream:
      bindings:
        city-in-0.destination: sample-topic
        city-out-0.destination: city-topic
        state-in-0.destination: sample-topic
        state-out-0.destination: state-topic
      function:
        definition: city;state
    kafka:
      streams:
        binder:
          brokers: localhost:9092